// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7Erc8MV5y5EslTnafvb0jMDTAx3SxJ2c',
    appId: '1:1013113776657:web:039004a04e19f30dae9fb0',
    messagingSenderId: '1013113776657',
    projectId: 'moon--knight',
    authDomain: 'moon--knight.firebaseapp.com',
    storageBucket: 'moon--knight.appspot.com',
    measurementId: 'G-RYTFPQT8MN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCE1obQWmwlblCwR_RWhO5eaxECCVXz7FU',
    appId: '1:1013113776657:android:2da1d14c6bc1e473ae9fb0',
    messagingSenderId: '1013113776657',
    projectId: 'moon--knight',
    storageBucket: 'moon--knight.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAO95gTx5nf2NqH1L-1LgRMVmMIITvce_8',
    appId: '1:1013113776657:ios:cc8cf304357e39edae9fb0',
    messagingSenderId: '1013113776657',
    projectId: 'moon--knight',
    storageBucket: 'moon--knight.appspot.com',
    androidClientId: '1013113776657-dochki260ogghaie9r0lrfnku4t8sq1m.apps.googleusercontent.com',
    iosClientId: '1013113776657-ge0hf3nq6j6t4efilnmprb3af5a0gub4.apps.googleusercontent.com',
    iosBundleId: 'io.dracula.moonknight',
  );
}
